# Generated by Django 3.2.7 on 2021-10-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='visibilidad',
            field=models.BooleanField(default=0),
        ),
    ]
