# Generated by Django 3.2.7 on 2021-10-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management_app', '0002_organizacion_visibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='visibilidad',
            field=models.BooleanField(default=1),
        ),
    ]
