# Generated by Django 3.2.8 on 2021-10-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management_app', '0003_alter_organizacion_visibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='pagina_web',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
